name: Update JSON Files

on:
  schedule:
    - cron: '0 */10 * * *'  # Runs every 10 hours
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch JSON files
        run: node fetch-json-files.js
        env:
          TDX_APP_ID: ${{ secrets.TDX_APP_ID }}
          TDX_APP_KEY: ${{ secrets.TDX_APP_KEY }}

      - name: Check for changes
        id: changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add json-files/
          if git diff --cached --exit-code; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changed == 'true'
        run: |
          echo "Committing changes..."
          git commit -m "Update JSON files"
          echo "Pushing changes..."
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/kting0/munisaq-api-fetcher.git
